### ISSUE TITLE
Issue with Dev VM version 1.1.17

### ISSUE THREAD

**Issue by shekharshank** [RIAPS/riaps-integration#60]
The User interface for XUbuntu Dev VM does not show up with https://riaps.isis.vanderbilt.edu/downloads/1.1.17/riaps-devbox-v1-1-17.vmdk.xz

It works with 1.1.16 release

**Comment by MMetelko** [comment]
It should be the same as 1.1.16 release, others have successfully run from this download.  More information would be needed to assist in this issue.

**Comment by shekharshank** [comment]
I am using VMware workstation 14 player on windows 10 OS.  This is what happens, it doesn't show the login screen. It is working fine with 1.1.16. I can try with virtualbox and let you know the result if that helps - 

![image](https://user-images.githubusercontent.com/3200787/80837461-d0bb2d00-8bc4-11ea-90a4-9dc526dd511f.png)

**Comment by shekharshank** [comment]
Virtualbox -

![image](https://user-images.githubusercontent.com/3200787/80838053-1a584780-8bc6-11ea-8d47-c0b51a577318.png)

**Comment by MMetelko** [comment]
Unfortunately we do not resources at this time to support other platforms, we have been working with VirtualBox for releases.  Tests have been done in a previous release to make sure that the releases work on VMWare which is why we release a .vmdk file with Guest Additions and other host to system interfaces turned off.  It has been at least a year since this testing was done and I would expect that the VMWare player has evolved.
